# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-20 18:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='Ninguno', max_length=20, null=True)),
                ('FechadeCreacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('FechadeModificacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='Ninguno', max_length=15, null=True)),
                ('Precio', models.FloatField(default='0.0', null=True)),
                ('Existencia', models.IntegerField(default=1, null=True)),
                ('Referencia', models.CharField(default='Ninguna', max_length=15, null=True)),
                ('descripcion', models.CharField(default='Ninguna', max_length=30, null=True)),
                ('Imagen', models.ImageField(default='', null=True, upload_to='Productos/Imagenes/')),
                ('FechadeCreacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('FechadeModificacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Categoria', models.ForeignKey(default='Sin Categoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.Categoria')),
            ],
        ),
    ]
